version: '3.6'
services:
  etcd:
    image: bitnami/etcd:3.4.3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=test
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=m3db-etcd-cluster

  m3db:
    image: quay.io/m3db/m3dbnode
    hostname: test
    command: ["-f", "/etc/m3/m3node.yaml"]
    ports:
      - "9000-9004:9000-9004"
      - "2379-2380:2379-2380"
    cap_add:
      - SYS_RESOURCE
    volumes:
      - m3db:/var/lib/m3db
      - ./config:/etc/m3

  m3coordinator:
    image: quay.io/m3db/m3coordinator
    command: ["-f", "/etc/m3/m3coordinator.yaml"]
    ports:
      - "7201:7201"
      - "7203:7203"
    volumes:
      - ./config:/etc/m3
  
  prom:
    image: prom/prometheus
    ports:
     - 9090:9090
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/dashboard.json:/etc/grafana/provisioning/dashboards/m3db.json
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/prom.yml

volumes:
  m3db:
