version: '3.6'
services:
  etcd:
    image: bitnami/etcd:3.4.3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=m3etcd
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=m3db-etcd-cluster
    volumes:
      - etcd:/bitnami/etcd/data/

  m3db:
    image: quay.io/m3db/m3dbnode:v0.15.0
    hostname: m3db-01
    command: ["-f", "/etc/m3/m3node.yaml"]
    restart: always
    ports:
      - "9000-9004:9000-9004"
      - "2379-2380:2379-2380"
    cap_add:
      - SYS_RESOURCE
    volumes:
      - m3db:/var/lib/m3db
      - ./config:/etc/m3
    depends_on:
      - etcd

  m3coordinator-admin:
    image: quay.io/m3db/m3coordinator:v0.15.0
    hostname: m3coordinator-admin
    command: ["-f", "/etc/m3/m3coordinator-admin.yaml"]
    ports:
      - "7201:7201"
    volumes:
      - ./config:/etc/m3
    depends_on:
      - m3db

  m3coordinator01:
    image: quay.io/m3db/m3coordinator:v0.15.0
    hostname: m3coordinator-01
    command: ["-f", "/etc/m3/m3coordinator.yaml"]
    restart: always
    volumes:
      - ./config:/etc/m3
    depends_on:
      - m3db
  
  m3aggregator01:
    image: quay.io/m3db/m3aggregator:v0.15.0
    hostname: m3aggregator01
    command: ["-f", "/etc/m3/m3aggregator.yaml"]
    restart: always
    environment:
      M3AGGREGATOR_HOST_ID: m3aggregator01
    ports:
      - "6002:6002"
    volumes:
      - ./config:/etc/m3
    depends_on:
      - m3coordinator01

  prom-0:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - m3coordinator01

  prom-1:
    image: prom/prometheus
    ports:
      - 9091:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - m3coordinator01

  prom-read:
    image: prom/prometheus
    ports:
      - 9092:9090
    volumes:
      - ./config/prometheus-remote-read.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - m3coordinator01


  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
    ports:
      - 3000:3000
    volumes:
      - ./grafana/m3dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/prom.yml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yml

volumes:
  m3db:
  etcd:
