global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
      team: 'badkonak'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'coordinator'
    static_configs:
      - targets: ['m3coordinator:7203']
  - job_name: 'm3db'
    static_configs:
      - targets: ['m3db:9004']

remote_write:
  - url: "http://m3db:7201/api/v1/prom/remote/write"
