listenAddress:
  type: "config"
  value: "0.0.0.0:7201"

logging:
  level: info

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

tagOptions:
  idScheme: quoted

ingest:
  ingester:
    workerPoolSize: 1000
    opPool:
      size: 1000
    retry:
      maxRetries: 3
      jitter: true
    logSampleRate: 0.01
  m3msg:
    server:
      listenAddress: "0.0.0.0:7507"
      retry:
        maxBackoff: 10s
        jitter: true

downsample:
  remoteAggregator:
    client:
      placementKV:
        namespace: /placement
      placementWatcher:
        key: m3aggregator
        initWatchTimeout: 10s
      hashType: murmur32
      shardCutoffLingerDuration: 1m
      flushSize: 1440
      maxTimerBatchSize: 1120
      queueSize: 10000
      queueDropType: oldest
      encoder:
        initBufferSize: 2048
        maxMessageSize: 10485760
        bytesPool:
          buckets:
            - capacity: 2048
              count: 4096
            - capacity: 4096
              count: 4096
          watermark:
            low: 0.7
            high: 1.0
      connection:
        writeTimeout: 250ms

clusters:
   - namespaces:
       - namespace: unagg
         # a week 168h
         retention: 1m
         type: unaggregated
       - namespace: metrics_1m_24h
         type: aggregated
         retention: 24h
         resolution: 1m
     client:
       config:
         service:
           env: default_env
           zone: embedded
           service: m3db
           cacheDir: /var/lib/m3kv
           etcdClusters:
             - zone: embedded
               endpoints:
                 - etcd:2379
       writeConsistencyLevel: majority
       readConsistencyLevel: unstrict_majority
       writeTimeout: 10s
       fetchTimeout: 15s
       connectTimeout: 20s
       writeRetry:
         initialBackoff: 500ms
         backoffFactor: 3
         maxRetries: 2
         jitter: true
       fetchRetry:
         initialBackoff: 500ms
         backoffFactor: 2
         maxRetries: 3
         jitter: true
       backgroundHealthCheckFailLimit: 4
       backgroundHealthCheckFailThrottleFactor: 0.5
