global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    prometheus_replica: "replica-0"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'coordinator'
    static_configs:
      - targets: ['m3coordinator01:7203']
  - job_name: 'aggregator'
    static_configs:
      - targets: ['m3aggregator01:6002']
  - job_name: 'm3db'
    static_configs:
      - targets: ['m3db:9004']

remote_write:
  - url: "http://m3coordinator01:7201/api/v1/prom/remote/write"
    write_relabel_configs:
      - regex: prometheus_replica
        action: labeldrop
